version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: city_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=UTC

volumes:
  pgdata:
