version: '3.8'

services:
  server:
    build: .
    network_mode: "host"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=UTC
      - TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      - TELEGRAM_CHAT_IDS: "${TELEGRAM_CHAT_IDS}"
