server:
  address: "0.0.0.0:8082"

database:
  dsn: "host=localhost user=city_user password=code1234 dbname=city_server port=5432 sslmode=disable"


assets:
  storage_path: "./data/assets"

auth:
  hmac_secret: "${HMAC_SECRET}"
  api_token: "super-secret-token"

notification:
  telegram_bot_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: -1001234567890  # ID группы, куда бот отправляет сообщения