server:
  address: "localhost:8080"

database:
  dsn: "host=host.docker.internal user=postgres dbname=city_server password=code1234 sslmode=disable"

assets:
  storage_path: "./data/assets"

auth:
  hmac_secret: "${HMAC_SECRET}"
  api_token: "super-secret-token"

notification:
  telegram_bot_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: -1001234567890  # ID группы, куда бот отправляет сообщения